### PR TITLE
Feature#bound date

### LINKED ISSUE #423: Support for durationTime to be a datetime instead of just time
Case in point:
I'm using jquery datepicker + jquery-timepicker to set the starting date of a meeting and then I have the end date. I want to show the duration of the meeting so that when it spans several days it still shows a correct duration. 

I believe the best way to achieve this is to also support somehow to pass a date/time as a durationTime instead of just the time.

The calculation shouldn't be too hard to do using moment.js...

### PR DESCRIPTION
**Pull request by QuentinFchx**
`boundDate` is a date object bound to the selected time. Its purpose is to be computed against `durationTime` to be able to display a duration over 24h.

I also linted the file:
eqeqeq, `pad2` + `stepval` not used, loop var declared as global.

TODO: boundDate description for the README.

Closes #423

### CODE REVIEW

**Comment by jonthornton** [comment]
I'm having trouble understanding the new code. Can you add some code comments?

**Comment by QuentinFchx** [comment]
I added a few comments, tell me what is not clear enough.
The whole idea is to be able to provide a date object to which belong the time being selected by the picker.
If it is provided, we assume that `durationTime` is also a full date object.
`_time2int` remove the date information so we keep it under `durDate`

**Comment by QuentinFchx** [comment]
Make sure you review this commit https://github.com/QuentinFchx/jquery-timepicker/commit/daf8e68570b1259d9a5f0e7faf9e628edd803876
I also included a "lint" commit but the whole diff might be difficult to review.

**Comment by QuentinFchx** [comment]
@jonthornton Do you think you'll find the time to review this one ?
I can use my own fork but I think the feature is good enough to make it to the main repo :smile:

**Comment by jonthornton** [comment]
It may have to wait until the weekend, but I'll get to it. Sorry for the
delay!

**Comment by QuentinFchx** [comment]
No worries, I already found an issue in my `_startOfDay` function :grin:

**Comment by QuentinFchx** [comment]
With those changes, I ran into an issue with time changes.
IE: winter time change is not taken into account while computing duration.

A better approach maybe to be able to pass a function to calculate `durationString`.
That way anyone could customize how to display durations.
```
function durationString(time){
    return '1day 2hours';
}
```
I will try this way.

**Comment by QuentinFchx** [comment]
I found another solution with passing a function to compute durationString. As this use case might be too specific, i'll go with my fork.
Sorry for the inconvenience !

**Comment by jonthornton** [comment]
That's a great idea!

**Pull request closed without merging**
